[google_credentials]
type = "service_account"
project_id = "sublime-lyceum-451409-r0" 
private_key_id = "7c8d7cba762b34992a8206020fda479510073752"
private_key =  """-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCX6vpVJYTxkKkE\nw7NCZVwupe0HMb06LVgtVhXYElBz0xPI5tVRfejjTsvbFtuq1uHqAHiqp2a1FIpZ\nx0atAHPz0/IJO1/3V9bVT7Tf8B7vprz7vEdazKdeKhtEtrIwyhwKvBdiVXpdg4n3\nQ6pjLSHdAW6ytIlw8fBSgYdrL1IkLCZWAifGQ/HZZYz0jYKCXpRnxPI4gCpFaG8N\nzYr31ee68LBDR0jFdOcWTeq8G8evg7xzOHKazkTNcPODqhDYH9B/8kX7/KHUHMc9\nWy9zuE8jaScMIYvbw7P3MErX+1o4W2YrHlwCn+UHYF6o3jst7ePEtGbp7ZAwDMCJ\nEqfsDtHtAgMBAAECggEAEXXKAjW+9xWRe3Dznh6wrtLWsHQ8w545C3LgrVYDhaBd\nnoI7Q7O1K8TfZKWWpyatzdtyguidAxRih0mCO7l42i4CnCGFGNQxZpBT4UYDhDc1\ncrhTuiGZ3dZ4jlfyGG3uNaSjCmP5HZzT40WVZHMoOHKk8qiRwFeqL41gD0dfyTTV\nXjgSEb/Q3xecccajszxE0uroSbAi9WmqFPapHC3DQRo2yjopft0I7Bp1rANqjmt0\nHr0xIpt5fxD2goda1LrJrR9X5+OaiyjTXOn4ZwUaloU60F0EitJ5eeUShdxASIlh\nAX+Ii8Jb7mujGquAPqNeEmT8umBLbDuLFvhw7quvQQKBgQDTJKM6wWCMRECAKCS/\nSKEoWm+CCRelOUiDq5SgKC4mi3PXwNsdp8O0Ip76TXO2jB2DXUjthlQzAOCfKRcJ\nVKSVOJjzJZbtWF5aFmJ28hCwE5RMsUV09q4FP4mAYCgc9tEOXU8aodsr9OaSCdIN\nNIV8IqgW8GpwNxx8nCiMU62TLQKBgQC4MUeIaiYEHnQch6Z5xDjGzM9Ip6P5rmRw\nFRJZB1BKdt7PGNWfg0MJbo0R8c00Pn7JL1A+P79OcHfoOU4zmcGFL9iayfmCU4qc\ntYuEg9AP+uSewVY5wRDyuMEkat3hgZ4jmpKUCIynk4XWoxamigCkrpzjxchufYpr\nloj1bqxxwQKBgGfAvSUGGTdT4o4XK9eDDQ4TQnAXn7Lk7ykkiygYFnWCWS5P6lws\nMBK4YH6GyLGPMIF4uXleZMmbSMVtH5DKMwXQhfgVJJEEt3h1P3VLhb/AH0OAaK0M\n+n5BtoOKvKte7WOtnk1r85MqCJMCmGE8ycsyDH8ZLHRv4GOrKJGsHMMRAoGAQd39\ngp7S8W4if4FS2wB8fTsIdSbd0I+4gwxF/2hKIhbYHp725Y//DQRnlh8uDpy6oh81\nRs1tEBPQDU9Q08sMFSDDCLdpbl2Jl/ij58NrSAukbdEdkJGmCeZfyzIcHmRHtNu1\nxxI3mkV6+wJfOzbme/2lRR6ZSknCki7G0128dQECgYABG2W8q6abibVYWpyCcTMQ\ntAmclBK9TSgWxfknXQx4mYBODb2/Y4Sz1Qb+9Racsbz8+qqTJcXQj4Y6rwqzmTFp\nTCmlGtESmq0dY1SCUumSFswDpwvLmGSVuYhqtC1ndMta1h2pOG0a37t45QLLEe3A\ny/QVaTRptA1UB2VK85WDww==\n-----END PRIVATE KEY-----\n"""
client_email = "evalmate@sublime-lyceum-451409-r0.iam.gserviceaccount.com"
client_id = "102670448183036061170"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/evalmate%40sublime-lyceum-451409-r0.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
 
[teachers]
teacher1 = "pass@123"
teacher2 = "pass@123"
 
[students]
student1 = "s1"
student2 = "s2"
student3 = "s3"
student4 = "s4"
student5 = "s5"